//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2551.01.07 at 12:40:10 ��͹���§ ICT 
//


package org.opencare.lib.model.edxl;

import org.apache.abdera.model.Element;


/**
 * Java content class for valueListType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/c:/Documents%20and%20Settings/nontster/Desktop/EDXL-DE_Schema_v1.0.xsd line 72)
 * <p>
 * <pre>
 * &lt;complexType name="valueListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="valueListUrn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ValueList extends Element {


    /**
     * Gets the value of the Value property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the Value property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.String}
     * 
     */
    String getValue();

    /**
     * Gets the value of the valueListUrn property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    String getValueListUrn();

    /**
     * Sets the value of the valueListUrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setValueListUrn(String value);

    void setValue(String value);
}
