//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2551.01.07 at 12:40:10 ��͹���§ ICT 
//


package org.opencare.lib.model.edxl;

import java.util.List;

import org.apache.abdera.model.Element;
import org.apache.abdera.model.ExtensibleElement;
import org.opencare.lib.model.cap.Alert;


/**
 * Java content class for xmlContentType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/c:/Documents%20and%20Settings/nontster/Desktop/EDXL-DE_Schema_v1.0.xsd line 57)
 * <p>
 * <pre>
 * &lt;complexType name="xmlContentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="keyXMLContent" type="{urn:oasis:names:tc:emergency:EDXL:DE:1.0}anyXMLType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="embeddedXMLContent" type="{urn:oasis:names:tc:emergency:EDXL:DE:1.0}anyXMLType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface XmlContent extends ExtensibleElement, Element{

	List<EmbeddedXMLContent> getEmbeddedXMLContent();
    EmbeddedXMLContent addEmbeddedXMLContent();    

    String[] getKeyXMLContent();
    void addKeyXMLContent(String value);
    void addKeyXMLContents(String... values);

}
