//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2551.01.07 at 12:40:10 ��͹���§ ICT 
//


package org.opencare.lib.model.edxl;

import java.util.List;

import org.apache.abdera.model.Element;
import org.apache.abdera.model.ExtensibleElement;


/**
 * Java content class for contentObjectType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/c:/Documents%20and%20Settings/nontster/Desktop/EDXL-DE_Schema_v1.0.xsd line 27)
 * <p>
 * <pre>
 * &lt;complexType name="contentObjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contentDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contentKeyword" type="{urn:oasis:names:tc:emergency:EDXL:DE:1.0}valueListType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="incidentID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="incidentDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="originatorRole" type="{urn:oasis:names:tc:emergency:EDXL:DE:1.0}valueListType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="consumerRole" type="{urn:oasis:names:tc:emergency:EDXL:DE:1.0}valueListType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="confidentiality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="nonXMLContent" type="{urn:oasis:names:tc:emergency:EDXL:DE:1.0}nonXMLContentType"/>
 *           &lt;element name="xmlContent" type="{urn:oasis:names:tc:emergency:EDXL:DE:1.0}xmlContentType"/>
 *         &lt;/choice>
 *         &lt;any/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ContentObject extends ExtensibleElement, Element {

	
    /**
     * Gets the value of the contentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    String getContentDescription(); 
    
    /**
     * Sets the value of the contentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setContentDescription(String value);
    
    /**
     * Gets the value of the ContentKeyword property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ContentKeyword property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentKeyword().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EDXL_DE_Schema_v1_0.ValueList}
     * 
     */
    List<ValueList> getContentKeywords();
    
    String  getContentKeyword(String name);
        
    void addContentKeyword(String name, String value);
    
    void addContentKeyword(ValueList keyword);
    
    /**
     * Gets the value of the incidentID property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    String getIncidentID();    
   
    /**
     * Sets the value of the incidentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIncidentID(String value);
    
	/**
     * Gets the value of the incidentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    String getIncidentDescription();
    
    /**
     * Sets the value of the incidentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIncidentDescription(String value);

    /**
     * Gets the value of the OriginatorRole property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the OriginatorRole property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOriginatorRole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EDXL_DE_Schema_v1_0.ValueList}
     * 
     */
    List<ValueList> getOriginatorRoles();
    
    String getOriginatorRole(String name);

    void addOriginatorRole(String name, String value);
    
    void addOriginatorRole(ValueList role);
    
    /**
     * Gets the value of the ConsumerRole property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ConsumerRole property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConsumerRole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EDXL_DE_Schema_v1_0.ValueList}
     * 
     */
    List<ValueList> getConsumerRoles();
    
    String getConsumerRole(String name);

    void addConsumerRole(String name, String value);
    
    void addConsumerRole(ValueList role);
    
    /**
     * Gets the value of the confidentiality property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    String getConfidentiality();

    /**
     * Sets the value of the confidentiality property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setConfidentiality(String value);
    
    /**
     * Gets the value of the xmlContent property.
     * 
     * @return
     *     possible object is
     *     {@link EDXL_DE_Schema_v1_0.XmlContent}
     */
    XmlContent getXmlContent();

    /**
     * Sets the value of the xmlContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link EDXL_DE_Schema_v1_0.XmlContent}
     */
    XmlContent setXmlContent();

    /**
     * Gets the value of the nonXMLContent property.
     * 
     * @return
     *     possible object is
     *     {@link EDXL_DE_Schema_v1_0.NonXMLContentType}
     */
    NonXMLContentType getNonXMLContent();

    /**
     * Sets the value of the nonXMLContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link EDXL_DE_Schema_v1_0.NonXMLContentType}
     */
    void setNonXMLContent(NonXMLContentType value);

}
