//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2551.01.07 at 12:40:10 ��͹���§ ICT 
//


package org.opencare.lib.model.edxl;

import org.apache.abdera.model.Element;
import org.apache.abdera.model.ExtensibleElement;


/**
 * Java content class for nonXMLContentType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/c:/Documents%20and%20Settings/nontster/Desktop/EDXL-DE_Schema_v1.0.xsd line 47)
 * <p>
 * <pre>
 * &lt;complexType name="nonXMLContentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mimeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="digest" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="contentData" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface NonXMLContentType extends ExtensibleElement, Element {


    /**
     * Gets the value of the digest property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getDigest();

    /**
     * Sets the value of the digest property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setDigest(java.lang.String value);

    /**
     * Gets the value of the mimeType property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMimeType();

    /**
     * Sets the value of the mimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMimeType(java.lang.String value);

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getUri();

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setUri(java.lang.String value);

    /**
     * Gets the value of the contentData property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    byte[] getContentData();

    /**
     * Sets the value of the contentData property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    void setContentData(byte[] value);

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger}
     */
    java.math.BigInteger getSize();

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger}
     */
    void setSize(java.math.BigInteger value);

}
