//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2551.01.07 at 12:40:10 ��͹���§ ICT 
//

package org.opencare.lib.model.edxl;

import org.apache.abdera.model.Element;

/**
 * Java content class for valueSchemeType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this java content object. (defined at
 * file:/c:/Documents%20and%20Settings/nontster/Desktop/EDXL-DE_Schema_v1.0.xsd
 * line 79)
 * <p>
 * 
 * <pre>
 * &lt;complexType name=&quot;valueSchemeType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;explicitAddressScheme&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;explicitAddressValue&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 */
public interface ValueScheme extends Element {

	String getExplicitAddressScheme();

	void setExplicitAddressScheme(String value);


	String[] getExplicitAddressValue();

	void addExplicitAddressValue(String value);

	void addExplicitAddressValues(String... values);

}
